# -*- coding: utf-8 -*-
"""a_very_big_sum.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mT0yNZOToAkfzj8LeZze4boOQdq2WdhX
"""

"""
Problem: A Very Big Sum
Category: Warmup
Platform: HackerRank

Description:
You are given an array of integers. Compute and return the sum of the elements.
The array may contain very large integers, so ensure the sum doesn't overflow.

Example:
Input: [1000000001, 1000000002, 1000000003, 1000000004, 1000000005]
Output: 5000000015
"""

def a_very_big_sum(ar):
    return sum(ar)

if __name__ == "__main__":
    # Example usage
    ar = [1000000001, 1000000002, 1000000003, 1000000004, 1000000005]
    result = a_very_big_sum(ar)
    print("Sum of array:", result)  # Output: 5000000015