# -*- coding: utf-8 -*-
"""Birthday Cake Candles

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mT0yNZOToAkfzj8LeZze4boOQdq2WdhX
"""

"""
Problem: birthday cake candles
diff:easy


"""
def birthdayCakeCandles(candles):
    candles.sort(reverse=True)
    tall=candles[0]
    count=0
    for i in candles:
        if i==tall:
            count+=1
        else:
            break
    print(count)
if __name__ == '__main__':

    candles_count = int(input().strip())
    candles = list(map(int, input().rstrip().split()))
    result = birthdayCakeCandles(candles)