# -*- coding: utf-8 -*-
"""Diagonal Difference

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mT0yNZOToAkfzj8LeZze4boOQdq2WdhX
"""

"""
Problem: Diagonal Difference


"""
n = int(input().strip())

arr = []

for _ in range(n):
    arr.append(list(map(int, input().rstrip().split())))
#arr = [[11, 2, 4], [4, 5, 6], [10, 8, -12]]
ltor=0
rtol=0

i=0
e=-1
while i<len(arr):
    ltor+=arr[i][i]
    rtol+=arr[e][i]

    i+=1
    e-=1

if rtol>ltor:
    print(rtol-ltor)
else:
    print(ltor-rtol)