# -*- coding: utf-8 -*-
"""Grading Students

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mT0yNZOToAkfzj8LeZze4boOQdq2WdhX
"""

"""
Problem: Grading Students
diff:easy


"""
def gradingStudents(grades):
    for i in grades:
        if i<38:
            print(i)
        else:
            if i%5==0:
                print(i)
            elif (i+1)%5==0:
                print(i+1)
            elif (i+2)%5==0:
                print(i+2)
            else:
                print(i)

if __name__ == '__main__':
    grades_count = int(input().strip())
    grades = []
    for _ in range(grades_count):
        grades_item = int(input().strip())
        grades.append(grades_item)

    result = gradingStudents(grades)