# -*- coding: utf-8 -*-
"""mini-max sum

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mT0yNZOToAkfzj8LeZze4boOQdq2WdhX
"""

"""
Problem: mini_max sum
diff:easy


"""
def miniMaxSum(arr):
    arr.sort()
    max=arr[-1]
    min=arr[0]

    for i in range(1,4):
        max+=arr[i]
        min+=arr[i]
    print(min,max)

if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)