# -*- coding: utf-8 -*-
"""Plus Minus

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mT0yNZOToAkfzj8LeZze4boOQdq2WdhX
"""

"""
Problem: Plus Minus


"""
def plusMinus(arr):
    pos=0
    neg=0
    zero=0
    for i in arr:
        if i>0:
            pos+=1
        elif i<0:
            neg+=1
        else:
            zero+=1
    print(pos/len(arr))
    print(neg/len(arr))
    print(zero/len(arr))

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)