# -*- coding: utf-8 -*-
"""staircase

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mT0yNZOToAkfzj8LeZze4boOQdq2WdhX
"""

"""
Problem: staircase
diff:easy


"""
def staircase(n):
    x=1
    while n>0:
        print(" "*(n-1)+"#"*x)
        n-=1
        x+=1

if __name__ == '__main__':
    n = int(input().strip())

    staircase(n)