# -*- coding: utf-8 -*-
"""time conversion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mT0yNZOToAkfzj8LeZze4boOQdq2WdhX
"""

"""
Problem: time conversion
diff:easy


"""
def timeConversion(s):
    hour=int(s[0:2])
    rest=s[2:8]
    if s[-2]=="A":
        if hour==12:
            hour=0
            print(str(hour)+rest)
        else:
            print(s)
    else:
        if hour!=12:
            hour+=12
            print(str(hour)+rest)
        else:
            print(s)

if __name__ == '__main__':
    s = input()
    result = timeConversion(s)